version: 2.1
jobs:
  test:
    docker:
      - image: docker run -it --rm --ipc=host mcr.microsoft.com/playwright:focal /bin/bash
        auth:
          username: 221220001212
          password: ShakhMAN12!  # context / project UI env-var reference
    steps:
      - run: npm install && npm i -D @playwright/test && npx playwright install && npx playwright test 
 
# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - test
