# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/playwright:focal
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install
            npm ci
            npm i -D @playwright/test
  run_tests:
    docker:
      - image: mcr.microsoft.com/playwright:focal
    environment:
      NODE_ENV: development
    steps:
      - run:
          name: Run Tests
          command: npm test
      - store_test_results:
          path: ./src/playwright-report
      - store_artifacts:
          path: ./src/playwright-report
workflows:
  build_tests:
    jobs:
      -build
      - run_tests
